name: Sebastian Thalhammer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36378
title: Sebastian Thalhammer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#301631'
    - '#c8c8c8'
    - '#cf7813'
    - '#027178'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
