name: Sebastian Thalhammer
favicon: null
layout_spectrum: 0.23433
typography_spectrum: 0.36378
title: Sebastian Thalhammer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#301631'
    - '#c8c8c8'
    - '#cf7813'
    - '#027178'
  brandStrength: 0.8125
  lightness: 0.2815351034514606
  saturation: 0.5200065083336085
  rhythmicContrast: 0.11656889831647277
purpose: []
