typography_spectrum: 0.38062
color:
  brandColors:
    - '#ffffff'
    - '#301631'
    - '#c8c8c8'
    - '#cf7813'
    - '#027178'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25977
analytics:
  google: null
  facebook: null
  twitter: null
name: Sebastian Thalhammer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sebastian Thalhammer
description: High Performance Coach
purpose: []
