name: Sebastian Thalhammer
layout_spectrum: 0.25977
typography_spectrum: 0.38062
cta: {}
analytics:
  google: UA-86102048-1
opengraph: {}
color:
  brandColors:
    - '#ffffff'
    - '#301631'
    - '#c8c8c8'
    - '#cf7813'
    - '#027178'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - type: external
    label: Work with Me
    url: 'https://calendly.com/thalhammer-sebastian/work-with-sebastian-thalhammer'
title: Sebastian Thalhammer
description: The Rainmaker
navigation:
  - name: About the Rainmaker
    id: 050468a0-087d-4b41-ae25-32e77dc3ad0a
    type: content
content: []
github: true
author:
  name: Sebastian Thalhammer
  email: sebastian@projektphoenix.com
  url: www.sebastianthalhammer.com
url: 'http://sebastianthalhammer.com'
