layout_spectrum: 0.5069935487255933
typography_spectrum: 0.5002416532721813
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.05455209594865394
  lightness: 0.24122973540484313
  saturation: 0.21010087972018165
  rhythmicContrast: 0.5617132105969704
name: Sebastian Thalhammer
cta: {}
analytics:
  google: UA-86102048-1
opengraph: {}
purpose:
  - type: external
    label: Work with Me
    url: 'https://calendly.com/thalhammer-sebastian/work-with-sebastian-thalhammer'
title: Sebastian Thalhammer
description: '"I help you find $10k in additional revenue within 30 days - guaranteed"'
navigation:
  - name: About
    id: 050468a0-087d-4b41-ae25-32e77dc3ad0a
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f05de352-c479-430b-9b60-bb9de33f7896.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f05de352-c479-430b-9b60-bb9de33f7896.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ce96da2c-9265-4d51-9e91-946f64a4e832.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ce96da2c-9265-4d51-9e91-946f64a4e832.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
author:
  name: Sebastian Thalhammer
  email: sebastian@projektphoenix.com
  url: www.sebastianthalhammer.com
url: 'http://sebastianthalhammer.com'
