layout_spectrum: 0.5069935487255933
typography_spectrum: 0.5002416532721813
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.05455209594865394
  lightness: 0.24122973540484313
  saturation: 0.21010087972018165
  rhythmicContrast: 0.5617132105969704
name: Sebastian Thalhammer
cta: {}
analytics:
  google: UA-86102048-1
opengraph: {}
purpose:
  - type: external
    label: Work with Me
    url: 'https://calendly.com/thalhammer-sebastian/work-with-sebastian-thalhammer'
title: Sebastian Thalhammer
description: '"I help you find 10k in additional revenue within 30 days - guaranteed"'
navigation:
  - name: About the Rainmaker
    id: 050468a0-087d-4b41-ae25-32e77dc3ad0a
    type: content
content: []
github: true
author:
  name: Sebastian Thalhammer
  email: sebastian@projektphoenix.com
  url: www.sebastianthalhammer.com
url: 'http://sebastianthalhammer.com'
